/*public class Seal extends Mammal implements LISTA_NAZW_INTERFEJSÓW_ODDZIELONYCH_PRZECINKAMI {
    ...
    //TUTAJ MUSZĄ WYSTĄPIĆ IMPLEMENTACJE WSZYSTKICH METOD ZADEKLAROWANYCH W IMPLEMENTOWANYCH INTERFEJSACH
}*/